services:
  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
    volumes:
      - ./qdrant_data:/qdrant/storage
    environment:
      - QDRANT__LOG_LEVEL=INFO

  ingestion:
    build: ./services/ingestion
    restart: unless-stopped
    environment:
      - LUNARCRUSH_API_KEY=${LUNARCRUSH_API_KEY}
      - QDRANT_HOST=qdrant
      - QDRANT_PORT=6333
      - SYMBOLS=BTC,ETH,SOL,XRP,DOGE
      - INGESTION_INTERVAL=1
    depends_on:
      - qdrant
    volumes:
      - ./logs:/app/logs
